#!/usr/bin/env python3
"""Generate WinUI XAML pass-1-like stubs (x:Name fields, InitializeComponent, event hookups)
so the project's C# can be type-checked on Linux without the Windows-only XAML compiler."""
import json, os, re, sys, glob
import xml.etree.ElementTree as ET

proj = sys.argv[1]
out = sys.argv[2]
winui = json.load(open(sys.argv[3]))
X = 'http://schemas.microsoft.com/winfx/2006/xaml'
DEFAULT = 'http://schemas.microsoft.com/winfx/2006/xaml/presentation'
pref = ['Microsoft.UI.Xaml.Controls', 'Microsoft.UI.Xaml.Controls.Primitives', 'Microsoft.UI.Xaml.Media',
        'Microsoft.UI.Xaml.Shapes', 'Microsoft.UI.Xaml.Documents', 'Microsoft.UI.Xaml.Media.Animation',
        'Microsoft.UI.Xaml.Media.Imaging', 'Microsoft.UI.Xaml', 'Microsoft.UI.Xaml.Input']
by_name = {}
for full in winui:
    ns, _, n = full.rpartition('.')
    by_name.setdefault(n, []).append(full)
all_winui_events = set(e for evs in winui.values() for e in evs)

# project events: "event <type> Name" declarations
proj_events = set()
for f in glob.glob(os.path.join(proj, '**', '*.cs'), recursive=True):
    if '/obj/' in f or '/bin/' in f: continue
    for m in re.finditer(r'\bevent\s+[^;=]*?\s(\w+)\s*;', open(f, encoding='utf-8-sig').read()):
        proj_events.add(m.group(1))
events = all_winui_events | proj_events

def resolve(tag, nsmap):
    ns, _, local = tag[1:].partition('}') if tag.startswith('{') else ('', '', tag)
    if ns == DEFAULT:
        for p in pref:
            if f'{p}.{local}' in winui: return f'global::{p}.{local}'
        if local in by_name: return 'global::' + by_name[local][0]
        return None
    if ns.startswith('using:'):
        return f'global::{ns[6:]}.{local}'
    return None

def xmlns_map(path):
    m = {}
    for ev, (prefix, uri) in ET.iterparse(path, events=['start-ns']):
        m[prefix] = uri
    return m

files = []
for path in glob.glob(os.path.join(proj, '**', '*.xaml'), recursive=True):
    if '/obj/' in path or '/bin/' in path: continue
    tree = ET.parse(path)
    root = tree.getroot()
    cls = root.get(f'{{{X}}}Class')
    if not cls: continue
    nsmap = xmlns_map(path)
    ns, _, name = cls.rpartition('.')
    fields, hooks = [], []
    idx = 0
    def walk(el, is_root):
        global idx
        tag = el.tag
        local = tag.split('}')[-1]
        if '.' in local:  # property element
            for c in el: walk(c, False)
            return
        t = resolve(tag, nsmap)
        fname = el.get(f'{{{X}}}Name') or el.get('Name')
        mod = el.get(f'{{{X}}}FieldModifier') or 'private'
        if mod.lower() == 'public': mod = 'public'
        elif mod.lower() == 'internal': mod = 'internal'
        else: mod = 'private'
        if fname and t and not is_root:
            fields.append(f'        {mod} {t} {fname} = null!;')
        for attr, val in el.attrib.items():
            if attr.startswith('{'): continue
            if attr in events and re.fullmatch(r'[A-Za-z_]\w*', val) and t:
                target = 'this' if is_root else (fname if fname else f'default({t})!')
                hooks.append(f'            {target}.{attr} += this.{val};')
        for c in el: walk(c, False)
    walk(root, True)
    body = '\n'.join(fields)
    hk = '\n'.join(hooks)
    code = f'''// <auto-generated stub for compile checking />
#nullable disable
namespace {ns}
{{
    partial class {name}
    {{
{body}
        public void InitializeComponent() {{ }}
        private void __StubConnect()
        {{
{hk}
        }}
    }}
}}
'''
    rel = os.path.relpath(path, proj).replace('/', '_')
    open(os.path.join(out, rel + '.g.cs'), 'w').write(code)
    files.append(rel)
open(os.path.join(out, '__Program.g.cs'), 'w').write('namespace __Stub { static class Program { static void Main() { } } }\n')
print(f'generated {len(files)} stubs')
