#!/usr/bin/env python3
"""Writes the compile-check project: the app's sources + generated XAML stubs, the app's package references,
and none of the Windows-only build steps (XAML compiler, CsWinRT projection, MSIX/PRI packaging)."""
import sys, xml.etree.ElementTree as ET

app_csproj, app_dir, out_path = sys.argv[1:4]
app = ET.parse(app_csproj).getroot()

def prop(name, default):
    el = app.find(f'.//{name}')
    return el.text if el is not None and el.text else default

refs = ''.join(
    f'    <PackageReference Include="{r.get("Include")}" Version="{r.get("Version")}" />\n'
    for r in app.iter('PackageReference'))

# nullable/style warnings are noise for this check; it exists to catch errors
nowarn = ';'.join(['CS8618', 'CS8602', 'CS8604', 'CS8600', 'CS8601', 'CS8603', 'CS8625', 'CS8619', 'CS8620', 'CS8622',
                   'CS1998', 'CS4014', 'CS0169', 'CS0649', 'CS0414', 'CS0162', 'CS0168', 'CS0219', 'CS8612', 'CS8767',
                   'CS8766', 'CS8765', 'CS0108', 'CS0067', 'CS8614', 'CS8631', 'CS9113', 'CS8509', 'CS0659', 'CS0660',
                   'CS0661', 'CS8321', 'CA1416', 'MVVMTK0045', 'MVVMTK0034', 'MVVMTK0033', 'MVVMTK0050', 'CsWinRT1030'])

open(out_path, 'w').write(f'''<Project Sdk="Microsoft.NET.Sdk">
  <!-- generated by Scripts/LinuxCompileCheck/make_csproj.py; do not edit -->
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>{prop("TargetFramework", "net9.0-windows10.0.22621.0")}</TargetFramework>
    <TargetPlatformMinVersion>{prop("TargetPlatformMinVersion", "10.0.18362.0")}</TargetPlatformMinVersion>
    <RootNamespace>{prop("RootNamespace", "FoxyBrowser716")}</RootNamespace>
    <AssemblyName>{prop("AssemblyName", "FoxyBrowser716")}</AssemblyName>
    <Platforms>x64</Platforms>
    <Platform>x64</Platform>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <LangVersion>{prop("LangVersion", "preview")}</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <WindowsAppSDKSelfContained>false</WindowsAppSDKSelfContained>
    <WindowsPackageType>None</WindowsPackageType>
    <EnableMsixTooling>false</EnableMsixTooling>
    <CsWinRTGenerateProjection>false</CsWinRTGenerateProjection>
    <CsWinRTEnabled>false</CsWinRTEnabled>
    <NoWarn>$(NoWarn);{nowarn}</NoWarn>
    <DefineConstants>$(DefineConstants);DISABLE_XAML_GENERATED_MAIN</DefineConstants>
    <StartupObject>__Stub.Program</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="{app_dir}/**/*.cs" Exclude="{app_dir}/obj/**;{app_dir}/bin/**" />
    <Compile Include="gen/*.cs" />
  </ItemGroup>
  <ItemGroup>
{refs}  </ItemGroup>
</Project>
''')
